receivers:
    otlp:
        protocols:
            grpc:
                endpoint: '0.0.0.0:4317'
                include_metadata: true
            http:
                endpoint: '0.0.0.0:4318'
                max_request_body_size: 0
                include_metadata: true
                cors:
                    allowed_origins:
                        - 'https://*'
                        - 'http://*'
                    allowed_headers:
                        - 'X-Highlight-Request'
                        - 'Origin'
                        - 'Content-Type'
                        - 'Accept'
                        - 'Traceparent'
                        - 'Tracestate'
                    max_age: 7200
exporters:
    otlphttp:
        endpoint: 'https://host.docker.internal:8082/otel'
        compression: snappy
        tls:
            insecure_skip_verify: true
        timeout: 30s
processors:
    batch:
        metadata_keys:
            - x-highlight-project
        metadata_cardinality_limit: 1000
        timeout: 1s
        send_batch_size: 1000
    attributes:
        actions:
            - key: highlight.project_id
              from_context: metadata.x-highlight-project
              action: insert
service:
    telemetry:
        logs:
            level: 'warn'
    extensions: [health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch, attributes]
            exporters: [otlphttp]
        metrics:
            receivers: [otlp]
            processors: [batch, attributes]
            exporters: [otlphttp]
        logs:
            receivers: [otlp]
            processors: [batch, attributes]
            exporters: [otlphttp]
extensions:
    health_check:
        endpoint: '0.0.0.0:4319'
        path: '/health/status'
