# Highlight.io services for the hobby deployment.
services:
    backend:
        container_name: backend
        image: ghcr.io/highlight/highlight-backend:docker-v0.5.6
        restart: on-failure
        ports:
            - '0.0.0.0:8082:8082'
        volumes:
            - highlight-data:/highlight-data
            - ../backend/env.enc:/build/env.enc
            - ../backend/env.enc.dgst:/build/env.enc.dgst
            - ../backend/localhostssl/server.key:/build/localhostssl/server.key
            - ../backend/localhostssl/server.crt:/build/localhostssl/server.crt
        env_file: .env

    frontend:
        container_name: frontend
        image: ghcr.io/highlight/highlight-frontend:docker-v0.5.6
        restart: on-failure
        volumes:
            - ../backend/localhostssl/server.key:/etc/ssl/private/ssl-cert.key
            - ../backend/localhostssl/server.pem:/etc/ssl/certs/ssl-cert.pem
            - ./nginx-hobby.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '0.0.0.0:3000:3000'
            - '0.0.0.0:6006:6006'
            - '0.0.0.0:8080:8080'
        env_file: .env

    collector:
        container_name: collector
        image: otel/opentelemetry-collector-contrib:0.128.0
        restart: on-failure
        ports:
            - '0.0.0.0:4317:4317'
            - '0.0.0.0:4318:4318'
        volumes:
            - ./collector-hobby.yml:/etc/otelcol-contrib/config.yaml

volumes:
    highlight-data:
